// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iutcnomoqigubmaaqliq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1dGNub21vcWlndWJtYWFxbGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzg5NTksImV4cCI6MjA2NjgxNDk1OX0.G8gS-hXKcZTVct7omxEQ84P4iNbe-cFU3PeH7AEm4G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});